name: ci

on:
  pull_request:
    branches:
      - stable

jobs:
  linter:
    strategy:
      matrix:
        zig-version:
          - latest
          - master
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          repository: "${{ github.event.pull_request.head.repo.full_name }}"
          ref: "${{ github.event.pull_request.head.ref }}"
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: "${{ matrix.zig-version }}"
          cache-key: "${{ github.job }}_${{ runner.os }}_zig-${{ matrix.zig-version }}_${{ matrix.repo || '' }}"
      - name: Check zig is canonical
        shell: 'bash'
        run: zig fmt --check .

  maintainance:
    strategy:
      matrix:
        zig-version:
          - latest
          - master
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          repository: "${{ github.event.pull_request.head.repo.full_name }}"
          ref: "${{ github.event.pull_request.head.ref }}"
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: "${{ matrix.zig-version }}"
          cache-key: "${{ github.job }}_${{ runner.os }}_zig-${{ matrix.zig-version }}_${{ matrix.repo || '' }}"

      - name: Test updating
        shell: 'bash'
        run: zig build -Dupdate -Dverbose

  user:
    strategy:
      matrix:
        zig-version:
          - latest
          - master
        repo:
          - glfw
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          repository: "${{ github.repository_owner }}/${{ matrix.repo }}.zig"
          ref: "${{ github.event.pull_request.base.ref }}"

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: "${{ matrix.zig-version }}"
          cache-key: "${{ github.job }}_${{ runner.os }}_zig-${{ matrix.zig-version }}_${{ matrix.repo || '' }}"

      - name: Prepare ${{ matrix.repo }}.zig/build.zig.zon
        env:
          URL: "git+${{ github.server_url }}/${{ github.event.pull_request.head.repo.full_name }}#${{ github.event.pull_request.head.sha }}"
        shell: 'bash'
        run: zig fetch --save "${URL}"

      - name: Test building ${{ matrix.repo }}.zig
        shell: 'bash'
        run: zig build -Dverbose
