name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v2
    - name: Check zig is canonical
      shell: bash
      run: |
        zig fmt --check .

  maintainance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Zig
      uses: mlugg/setup-zig@v2

    - name: Test updating
      shell: 'bash'
      run: |
        zig build -Dupdate -Dverbose

  user:
    strategy:
      matrix:
        repo:
          - glfw
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.repo }}.zig"

    - name: Setup Zig
      uses: mlugg/setup-zig@v2

    - name: Prepare ${{ matrix.repo }}.zig/build.zig.zon
      env:
        URL: "git+${{ github.server_url }}/${{ github.repository }}#${{ github.event.pull_request.head.sha }}"
      shell: 'bash'
      run: |
        zig fetch --save "${URL}"

    - name: Test building ${{ matrix.repo }}.zig
      shell: 'bash'
      run: |
        zig build -Dverbose
