name: cd ping

on:
  push:
    tags:
      - '*'

jobs:
  ping:
    permissions:
      contents: write
    strategy:
      matrix:
        repo:
          - glfw
    runs-on: ubuntu-latest
    steps:
    - uses: tiawl/spaceporn-action-cd-ping@v1.0.1
      with:
        from: "${{ github.event.repository.name }}"
        to: "${{ matrix.repo }}.zig"
        tag: "${{ github.ref_name }}"
        token: "${{ secrets.PAT }}"
